
package org.mule.hackathon2012.panel.request;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1.3
 * Sun Jun 17 17:37:55 PDT 2012
 * Generated source version: 2.1.3
 * 
 */

public final class IDataExtractService_DataExtractServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://researchnow.com/schema/panel/finance/extract/v1", "DataExtractService");

    private IDataExtractService_DataExtractServicePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = DataExtractService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        DataExtractService ss = new DataExtractService(wsdlURL, SERVICE_NAME);
        IDataExtractService port = ss.getDataExtractServicePort();  
        
        {
        System.out.println("Invoking panelDataExtractRequest...");
        org.mule.hackathon2012.header.MessageHeader _panelDataExtractRequest_messageHeader = null;
        org.mule.hackathon2012.panel.request.PanelDataExtractRequest _panelDataExtractRequest_panelDataExtractRequest = null;
        port.panelDataExtractRequest(_panelDataExtractRequest_messageHeader, _panelDataExtractRequest_panelDataExtractRequest);


        }

        System.exit(0);
    }

}
