package org.mule.hackathon2012.panel.request;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

import org.mule.hackathon2012.header.MessageHeader;

/**
 * This class was generated by Apache CXF 2.1.3
 * Sun Jun 17 17:37:55 PDT 2012
 * Generated source version: 2.1.3
 * 
 */
 
@WebService(targetNamespace = "http://researchnow.com/schema/panel/finance/extract/v1", name = "IDataExtractService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IDataExtractService {

    @Oneway
    @WebMethod(operationName = "PanelDataExtractRequest", action = "http://researchnow.com/schema/panel/finance/extract/v1/IDataExtractService/PanelDataExtractRequest")
    public void panelDataExtractRequest(
        @WebParam(partName = "MessageHeader", name = "MessageHeader", targetNamespace = "http://researchnow.com/schema/icc", header = true)
        MessageHeader messageHeader,
        @WebParam(partName = "PanelDataExtractRequest", name = "PanelDataExtractRequest", targetNamespace = "http://researchnow.com/schema/panel/finance/extract/v1")
        PanelDataExtractRequest panelDataExtractRequest
    );
}
