package org.mule.hackathon2012.scheduler;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import org.mule.hackathon2012.header.MessageHeader;

/**
 * This class was generated by Apache CXF 2.1.3
 * Sun Jun 17 16:07:21 PDT 2012
 * Generated source version: 2.1.3
 * 
 */
 
@WebService(targetNamespace = "http://researchnow.com/schema/panel/v1", name = "ISchedulerRequest")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ISchedulerRequest {

    @Oneway
    @WebMethod
    public void processExtractRequest(
        @WebParam(partName = "MessageHeader", name = "MessageHeader", targetNamespace = "http://researchnow.com/schema/icc", header = true)
        MessageHeader messageHeader,
        @WebParam(partName = "SchedulerExtractRequest", name = "SchedulerExtractRequest", targetNamespace = "http://researchnow.com/schema/panel/v1")
        SchedulerExtractRequest schedulerExtractRequest
    );
}
