
package org.mule.hackathon2012.scheduler;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1.3
 * Sun Jun 17 16:07:21 PDT 2012
 * Generated source version: 2.1.3
 * 
 */

public final class ISchedulerRequest_ISchedulerRequestPort_Client {

    private static final QName SERVICE_NAME = new QName("http://researchnow.com/schema/panel/v1", "ISchedulerRequestService");

    private ISchedulerRequest_ISchedulerRequestPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = ISchedulerRequestService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ISchedulerRequestService ss = new ISchedulerRequestService(wsdlURL, SERVICE_NAME);
        ISchedulerRequest port = ss.getISchedulerRequestPort();  
        
        {
        System.out.println("Invoking processExtractRequest...");
        org.mule.hackathon2012.header.MessageHeader _processExtractRequest_messageHeader = null;
        org.mule.hackathon2012.scheduler.SchedulerExtractRequest _processExtractRequest_schedulerExtractRequest = null;
        port.processExtractRequest(_processExtractRequest_messageHeader, _processExtractRequest_schedulerExtractRequest);


        }

        System.exit(0);
    }

}
