
/*
 * 
 */

package org.mule.hackathon2012.scheduler;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.1.3
 * Sun Jun 17 16:07:21 PDT 2012
 * Generated source version: 2.1.3
 * 
 */


@WebServiceClient(name = "ISchedulerRequestService", 
                  wsdlLocation = "file:src/main/resources/Scheduer-Request.wsdl",
                  targetNamespace = "http://researchnow.com/schema/panel/v1") 
public class ISchedulerRequestService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://researchnow.com/schema/panel/v1", "ISchedulerRequestService");
    public final static QName ISchedulerRequestPort = new QName("http://researchnow.com/schema/panel/v1", "ISchedulerRequestPort");
    static {
        URL url = null;
        try {
            url = new URL("file:src/main/resources/Scheduer-Request.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/Users/albinkjellin/studio/hackathon/hackathon3.3/src/main/resources/Scheduer-Request.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public ISchedulerRequestService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ISchedulerRequestService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ISchedulerRequestService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns ISchedulerRequest
     */
    @WebEndpoint(name = "ISchedulerRequestPort")
    public ISchedulerRequest getISchedulerRequestPort() {
        return super.getPort(ISchedulerRequestPort, ISchedulerRequest.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISchedulerRequest
     */
    @WebEndpoint(name = "ISchedulerRequestPort")
    public ISchedulerRequest getISchedulerRequestPort(WebServiceFeature... features) {
        return super.getPort(ISchedulerRequestPort, ISchedulerRequest.class, features);
    }

}
